#!/usr/bin/env node
/**
 * Derive the package's entry points from its component folders.
 *
 * Every `src/<name>/index.ts` is a component entry: it becomes
 * `@formwright/ui/<name>` in package.json and an import in `src/index.ts`,
 * which registers everything at once. Generated rather than hand-edited so
 * a component is added by adding its folder — nobody has to remember three
 * other files, and components built in parallel cannot collide on them.
 *
 *   node scripts/sync-exports.mjs          write
 *   node scripts/sync-exports.mjs --check  exit 1 if out of date (CI / tests)
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src");
const check = process.argv.includes("--check");

export function componentNames() {
  return readdirSync(SRC, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name !== "core")
    .filter((d) => existsSync(join(SRC, d.name, "index.ts")))
    .map((d) => d.name)
    .sort();
}

const entry = (path) => ({
  types: `./dist/${path}.d.ts`,
  import: `./dist/${path}.js`,
  require: `./dist/${path}.cjs`,
});

const names = componentNames();

const exportsField = {
  ".": entry("index"),
  "./core": entry("core/index"),
  ...Object.fromEntries(names.map((n) => [`./${n}`, entry(`${n}/index`)])),
  "./package.json": "./package.json",
};

const indexSource =
  `/**\n * @formwright/ui — every component, registered.\n *\n` +
  ` * GENERATED by scripts/sync-exports.mjs from the component folders. Do not\n` +
  ` * edit by hand; add a folder with an index.ts and run \`pnpm exports\`.\n *\n` +
  ` * Importing this registers every <fw-*> element. To ship only what a page\n` +
  ` * uses, import the component entries instead: \`@formwright/ui/select\`.\n */\n` +
  names.map((n) => `export * from "./${n}/index.js";`).join("\n") +
  `\nexport * from "./core/index.js";\n`;

const pkgPath = join(ROOT, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const nextPkg = `${JSON.stringify({ ...pkg, exports: exportsField }, null, 2)}\n`;
const indexPath = join(SRC, "index.ts");
const currentIndex = existsSync(indexPath) ? readFileSync(indexPath, "utf8") : "";

const pkgStale = readFileSync(pkgPath, "utf8") !== nextPkg;
const indexStale = currentIndex !== indexSource;

if (check) {
  if (pkgStale || indexStale) {
    console.error(
      "✗ @formwright/ui entry points are out of date. Run `pnpm --filter @formwright/ui exports`.",
    );
    process.exit(1);
  }
  console.log(`✓ ${names.length} component entries in sync`);
} else {
  writeFileSync(pkgPath, nextPkg);
  writeFileSync(indexPath, indexSource);
  console.log(`✓ wrote ${names.length} component entries: ${names.join(", ")}`);
}
