/**
 * @formwright/ui — every component, registered.
 *
 * GENERATED by scripts/sync-exports.mjs from the component folders. Do not
 * edit by hand; add a folder with an index.ts and run `pnpm exports`.
 *
 * Importing this registers every <fw-*> element. To ship only what a page
 * uses, import the component entries instead: `@formwright/ui/select`.
 */
export * from "./button/index.js";
export * from "./input/index.js";
export * from "./select/index.js";
export * from "./core/index.js";
